### PR TITLE
feat: add scalar integration (alternative to Redoc)

### PR DESCRIPTION
**Pull request by marclave**
hey y'all, we had a couple requests to integrate [Scalar](https://github.com/scalar/scalar) with Aide 🦀!

We had a lot of fun writing rust + making a super fun theme (check the animation on Ferris between light and dark mode toggle) 

some features:
- fully customizable themes
- offline search (through fuse.js)
- integrated API Testing Client
- modern look
- and more ✨ 

https://github.com/tamasfe/aide/assets/6176314/1b323a5b-b26a-431a-9d13-6916c9f8f8a2

you can also check it out here https://rust.apidocumentation.com/

i wasn't sure on the best way of integrating (i'm very new to rust) so i'm eager and excited for feedback!

Also I can start writing documentation once feedback is recieved ✨

### CODE REVIEW

**Comment by Wicpar** [comment]
Thank you for the PR, just revert the deletions in the example if there was no reason for it.

@tamasfe do you approve ? 
I'll do the merge and bump.

**Comment by marclave** [comment]
@Wicpar I added the deletions cause of this issue #103 , we need to handle this error in Scalar but I haven't had a moment to roll out the fix.

I deleted it since it doesnt add properly to the schemas and it causes an invalid swagger file as output (can see the thread on missing AppError schema)

Happy to remove but since it doesnt get generated we may want to remove it? Happy on whichever decision y'all think is best here ✨

**Comment by Wicpar** [comment]
Yes i posted the details. We can push a fix before merging this PR if you want :)

**Comment by marclave** [comment]
> Yes i posted the details. We can push a fix before merging this PR if you want :)

ah right, sorry haha I had way too much coffee today 👀 

i'll remove the deleted code and i'm happy to merge it with a fast follow ❤️

**Comment by Wicpar** [comment]
> > Yes i posted the details. We can push a fix before merging this PR if you want :)
> 
> ah right, sorry haha I had way too much coffee today 👀 
> 
> i'll remove the deleted code and i'm happy to merge it with a fast follow ❤️

And i need to sleep, i was wrong on the example thing :)

**Comment by marclave** [comment]
haha we can chat tomorrow @Wicpar ✨ 💤 

happy either way on the decision. I reverted the commented out code :)

**Review by Wicpar — COMMENTED** [review]
ah, forgot to mention that in commits `fix:` means a bug was fixed, it will be included in the changelog by the script, please use `chore:` instead for insubtsantial changes.
Squashing all three committs might be a good idea, imthink i can do that during merge

**Comment by Wicpar** [comment]
published in 0.13.2

**Comment by Wicpar** [comment]
@marclave Hi, i was wondering why the response schemas are not documented like the request bodies ? Any way to fix than ? other than that the interface has been great.

**Comment by marclave** [comment]
> @marclave Hi, i was wondering why the response schemas are not documented like the request bodies ? Any way to fix than ? other than that the interface has been great.

hi @Wicpar , appreciate the kind words! the response schemas should be rendering, would you be able to provide an example OpenAPI spec and I can investigate ✨

**Comment by Wicpar** [comment]
You can look at api.v2.ipocamp.io for my production api
But i checked and it doesn't work in your demo using the swagger pet shop either. The responses only have the example, not the interface to explore the schema like the request body has.

**Pull request merged**
