### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by jplatte**
… and collapse some lines in `Cargo.toml`s.

### CODE REVIEW

**Comment by JakkuSakura** [comment]
1. Should we put axum-jsonschema into its own repo?
2. As aide is a library, it's better not to rely on specific patch version, as in major.minor.patch. It's a good time to clean them up

**Comment by jplatte** [comment]
1. No idea, honestly. I don't care about it personally, so would probably default to doing nothing (keeping it here) for now. If you want to make a PR removing it from this repo, let's try to loop the original maintainers in for that decision?
2. I disagree. Specifying a minor/patch version only restricts the minimum, not the maximum version. Since we're not testing the minimum version in CI, I'd rather not lower it. See also https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by tamasfe** [comment]
> Should we put axum-jsonschema into its own repo?

#162, if it was up to me, I'd just move it to an archived repo and update the crates.io package with a notice.

**Comment by JakkuSakura** [comment]
> I disagree. Specifying a minor/patch version only restricts the minimum, not the maximum version. Since we're not testing the minimum version in CI, I'd rather not lower it.

I know this rule. I just had some crazy dependencies that specified =patch version. If they're incompatible, it's tricky to deal with them

**Review by JakkuSakura — APPROVED** [review]
Deal with axum-jsonschema in another PR

**Comment by qrilka** [comment]
> > Should we put axum-jsonschema into its own repo?
> 
> #162, if it was up to me, I'd just move it to an archived repo and update the crates.io package with a notice.

@tamasfe no notice on crates.io so far?

**Pull request merged**
