### PR TITLE
feat(aide): impl OperationInput for axum-tungstenite

### PR DESCRIPTION
**Pull request by snpschaaf**
Use the  `OperationInput` impl of `axum::extract::ws::WebSocketUpgrade` for `axum_tungstenite::WebSocketUpgrade` as well.

### CODE REVIEW

**Comment by Wicpar** [comment]
Does your use case not allow `NoApi` to be used ?

You can extract any regular axum type with it if it has no api definition.

`fn extract(NoApi(extracted): NoApi<TypeToExtract>)`

**Comment by snpschaaf** [comment]
In theory this would be a solution. But then there would be not API doc for a WebSocket endpoint in this particular case. So in practice I would love to see this change upstream ^^

What's your argument for not adding this?

**Comment by Wicpar** [comment]
We are having issues with conflicting versions, where some people need 0.5 and some 0.6 for sqlx for instance, so we had to pull the axum_sqlx_tx implementation out of the crate to allow for that. We are trying to keep dependencies to a minimum because of that, in favor of the new type pattern. 

If you need the definition you can use the `WithApi` struct, although it might be better suited without requiring new type implementations.

Would something like `UseApi(ws, ..): UseApi<tunstenite, axum::extract:ws>` where the first parameter is extracted and the api taken from the second work for you ?

**Comment by Wicpar** [comment]
Or you can do a new type `MyWs(pub tunstenite)` and then impl deref, operation input, and FromRequest

**Comment by snpschaaf** [comment]
Thanks for advice :)

I understand that you like to keep the dependencies minimal.

My brief opinion on the suggested solutions:
* The new tpye approach: per project: an extra wrapper to maintain; all projects: wrapper needs to keep in sync with aide (in case of breaking changes)
*  The `UseApi` approach is a nice thought, but I encourage to not implement this. It's very easy that changes are made and the definition is not updated as someone forget a  `UseApi`.
* IME `WithApi` usage causes the same "problems" as the  `UseApi` approach.

IMHO the impl of the  `OperationInput` within aide would be the cleanest solution. But if you don't like this, it is ok to me :) 
Either I keep a fork or I switch to the newtype approach.

**Comment by Wicpar** [comment]
If you have a generic UseApi you could type alias to keep both types in sync.

Even if you do the impl in the crate it would not be more in sync than a type aliased UseApi. Usage wise it implements Deref and DerefMut so it is almost a drop in replacement.

Feel free to try the UseApi i pushed to master, with a type alias it should work well in your usecase.

**Comment by snpschaaf** [comment]
Using the `UseApi` approach now. Thx :)

**Pull request closed without merging**
