### PR TITLE
add support for `jwt_authorizer` crate. Fix memory usage issue

### PR DESCRIPTION
**Pull request by 0xdeafbeef**

### CODE REVIEW

**Comment by 0xdeafbeef** [comment]
Fixes https://github.com/tamasfe/aide/issues/48

**Comment by 0xdeafbeef** [comment]
Fixes https://github.com/tamasfe/aide/issues/48

**Comment by imp** [comment]
FWIW - `jwt_authorizer` support would be really appreciated. Is there anything that can be done to help with getting this PR merged?

**Comment by tamasfe** [comment]
Thanks!

**Comment by tasn** [comment]
Probably not the right place to ask it, but looking at the code it looks like there's a way to add a transformation to operations on the axum extractor level? So e.g. every route that uses this auth extractor will get auth added to it, or am I missing something?

**Comment by tamasfe** [comment]
> Probably not the right place to ask it, but looking at the code it looks like there's a way to add a transformation to operations on the axum extractor level? So e.g. every route that uses this auth extractor will get auth added to it, or am I missing something?

Yes, it is possible, you can implement `OperationInput` for your own extractors and modify operations there. The only limitation of this approach is that you can only rely on types rather than concrete values out of the box (e.g. you can't specify oauth scope strings on a handler) , this can be worked around by custom types (possibly with macro magic to make it ergonomic), and will be much easier with const generics which are not expected to land in the foreseeable future.

**Comment by tasn** [comment]
Ah awesome, thanks a lot!

I just want to define "authenticated" on the authenticated extractor, what we currently do quite manually around the codebase.

**Pull request merged**
